### ISSUE TITLE
User workload monitoring does not honor volumeClaimTemplate

### ISSUE THREAD

**Issue by reggie-k** [openshift/cluster-monitoring-operator#1026]
I am trying to enable persistence for the user workload monitoring, running on OCP 4.5.
this is the confimap I am using:
```apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-standalone
          resources:
            requests:
              storage: 3Gi
```
The user prometheus is up fine, but no pvcs created (the storage class exists and the built-in prometheus works with it just fine).
Have  I misconfigured something in the configmap?

**Comment by lilic** [comment]
Hey @reggie-k that looks correct, but only works from 4.6 onwards. In 4.5 when user workload was still tech preview, you need to use the openshift-cluster-monitoring configmap under `prometheusUserWorkload `. Something like but I did not test this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    techPreviewUserWorkload:
      enabled: true
    prometheusUserWorkload:
            volumeClaimTemplate:
              spec:
                storageClassName: openebs-standalone
                resources:
                  requests:
                    storage: 3Gi
```

Hope that helps, if not feel free to turn to customer support person! :)
