### ISSUE TITLE
cluster-monitoring-config changes not being applied

### ISSUE THREAD

**Issue by whitleykeith** [openshift/cluster-monitoring-operator#1169]
I'm trying to configure the thanos sidecar present on the prometheus install to back up prom data to s3. As such, I've created a secret `thanos-s3-config` which has the right format. However, I don't see that being applied when I create a configmap like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      version: v.2.27.0
      thanos:
        objectStorageConfig: 
          key: config
          name: thanos-s3-config

```

I have the appropriate permissions in my cluster and I can see in the operator logs that it picks up an update and applies it successfully. However, the original prometheusK8s cr doesn't change and no pods cycle. I tried to do other things such as the prometheusK8s.version key with similar results.
