### ISSUE TITLE
RFE: add Additional  Scrap Configs to User Workload Monitoring

### ISSUE THREAD

**Issue by ljuaneda** [openshift/cluster-monitoring-operator#1201]
Hi,

The Prometheus Operator let you configure additional scrape configs => https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/additional-scrape-config.md
It is very usefull when you have targets outside the openshift cluster.

I've tried to modify the user-worload prometheus spec object, but  the CM operator erase the change ...

It should be an available option in the user-workload-monitoring-config configmap: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      additionalScrapeConfigs:
        name: additional-scrape-configs
        key: prometheus-additional.yaml
```

Regards,

Ludovic
