### ISSUE TITLE
 Grafana dashboard variable queries are failing when connecting tenancy as datasource

### ISSUE THREAD

**Issue by m-yosefpor** [openshift/cluster-monitoring-operator#1355]
Currently it's possible to add metrics of a specific namespace as a datasource to a grafana in a multi-tenant manner, via the `tenancy` port of `thanos-querier`, however the `prom-label-proxy` used in thanos-querier side-car in Openshift currently does not support  Grafana dashboard variable queries (e.g. `label_values(up, instance)` ), since these queries are of type `/api/v1/series`. Check [this github issue](https://github.com/prometheus-community/prom-label-proxy/issues/37) for more details. This is however supported since v0.3.0 (which I suppose is also supported in openshift fork of prom label proxy), however CMO should pass `--enable-label-apis` flag to prom-label-proxy side car when creating  `thanos-querier` deployment.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  ...
  name: thanos-querier
  namespace: openshift-monitoring
spec:
  template:
    metadata:
      spec:
        containers:
        - args:
          - --insecure-listen-address=127.0.0.1:9095
          - --upstream=http://127.0.0.1:9090
          - --label=namespace
          - --enable-label-apis # <<<<<<<<<<<<<<< here
          image: quay.io/openshift/okd-content@sha256:18c84b83f344333fd40351a046399132d7fc93ffac9100929a23ac5f564622e8
          name: prom-label-proxy
```
