### ISSUE TITLE
Enable AlertmanagerConfig CR processing with the cluster-monitoring-config ConfigMap

### ISSUE THREAD

**Issue by cgruver** [openshift/cluster-monitoring-operator#1375]
Caveat:  I realize that AlertmanagerConfig is not officially supported yet in OpenShift.  However, I would like to begin using the feature in an OKD lab cluster.

Is it possible to configure the Cluster Monitoring Operator to honor AlertManagerConfig CRs?

I have tried:

```bash
oc patch AlertManager main --patch '{"spec":{"alertmanagerConfigSelector":{"matchLabels":{"alertmanagerConfig":"pager-duty-apps"}}}}' --type=merge -n openshift-monitoring
```

But the operator naturally restores the configuration back to its managed state.

I have also tried adding the necessary configs to the `cluster-monitoring-config` ConfigMap.  But the operator appears to ignore those entries.

Is there a configuration that I can add that will enable this as an experimental feature?

**Comment by azerbe** [comment]
I'm also interested.

**Comment by GerbenWelter** [comment]
I have also been trying to solve this problem. I found a possible solution by digging through the CRDs to only find out that the operator reverted things like @cgruver did.

The [OpenShift docs](https://docs.openshift.com/container-platform/4.9/monitoring/configuring-the-monitoring-stack.html#monitoring-configuring-external-alertmanagers_configuring-the-monitoring-stack) hint at another possible solution: If you scroll down to 'To configure additional Alertmanager instances for routing alerts from user-defined projects' you can add additional AlertmanagerConfigs:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    <component>:
      additionalAlertmanagerConfigs:
      - <alertmanager_specification>
```
The <alertmanager_specification> seems to match [this specification](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Calertmanager_config%3E) but I can't get it to work.

Even if this were to work the solution tried by @cgruver would be cleaner. So I'm also in favor of fixing this.
