### ISSUE TITLE
How to monitor custom metrics okd 3.11 / Problem to add another target

### ISSUE THREAD

**Issue by danilorsilva** [openshift/cluster-monitoring-operator#156]
Hello All!

- I have a okd 3.11 installed with full stack of monitoring running perfect.

I would like to monitor custom metrics from my pods. I have a pod that exposes /prometheus path with some metrics and i would like to collect them to use to monitor and alarm.

I have configured a ServiceMonitor but without success. If i go to "Configuration" options on Prometheus web interface, i can see my custom configurations from my service monitor, but on " Targets" options, i cannot see my target there.

Can anyone help me? Thanks!

If you need some more details about the problem, please let me know.

**Comment by metalmatze** [comment]
Can you check if the label selectors of your ServieMonitor are matching the labels of your Service?

**Comment by danilorsilva** [comment]
Yes, the labels are okay,

**Comment by metalmatze** [comment]
Can you share the ServiceMonitor object? Did you also configure the endpoints path to scrape `/prometheus`? If one of these things in the ServiceMonitor do not match, it the target will be dropped during discovery.

**Comment by Rikbruggink** [comment]
@danilorsilva i have run in too the same problems while configuring heketi-metrics in the prometheus instance. Some tips to cross off your list if you are using the default Prometheus instance:

1) is the servicemonitoring in the correct space?
2) is the namespace/project correctly labeled to allow scraping
3) did you grant the prometheus service account the rights to use the selector in the servicemonitor?
4) What do the logs say from the prometheus pods and config-reloader?

**Comment by danilorsilva** [comment]
@Rikbruggink 

1 - The ServiceMonitor must be on the same namespace/project that the service that i want to scrape? Or the ServiceMonitor must be on openshit-monitoring namespace and only set the namespace target inside the servicemonitor file?
2 - I put `openshift.io/cluster-monitoring=true` label on the namespace.

**Comment by Rikbruggink** [comment]
>> The ServiceMonitor must be on openshit-monitoring namespace and only set the namespace target inside the servicemonitor file?

the servicemonitor must be in the openshift-monitoring namespace with a correct selector

**Comment by danilorsilva** [comment]
What i did:

I have a namespace named `test` and i set the label `openshift.io/cluster-monitoring=true` to be monitored by the CMO.

Inside this namespace i have a pod and a service. This service handle the requests to this pod.

I have created this servicemonitor:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: api-mobile-servicemonitor
  name: api-mobile-servicemonitor
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: 8080-tcp
    path: /prometheus
  namespaceSelector:
    matchNames:
    - test
  selector:
    matchLabels:
      app: api-mobile
```

The k8s-app is the label that i need to set on ServiceMonitor to be scraped bu Prometheus and load the configuration.
