### ISSUE TITLE
Why do my changes to the prometheus rules only work in a short time?

### ISSUE THREAD

**Issue by wenj1104** [openshift/cluster-monitoring-operator#158]
I edited the `prometheus-k8s-rules` prometheus rule,then I save it.
But after tens of seconds,the `prometheus-k8s-rules` prometheus rule became what it was before.

> before my change
```
# oc get prometheusrules prometheus-k8s-rules -o yaml | grep -A 3 -B 5 kubelet_running_pod
    - alert: KubeletTooManyPods
      annotations:
        message: Kubelet {{$labels.instance}} is running {{$value}} pods, close to
          the limit of 110.
      expr: |
        kubelet_running_pod_count{job="kubelet"} > 100
      for: 15m
      labels:
        severity: warning
```
> after my change
```
# oc get prometheusrules prometheus-k8s-rules -o yaml | grep -A 3 -B 5 kubelet_running_pod
    - alert: KubeletTooManyPods
      annotations:
        message: Kubelet {{$labels.instance}} is running {{$value}} pods, close to
          the limit of 110.
      expr: |
        kubelet_running_pod_count{job="kubelet"} > 90
      for: 15m
      labels:
        severity: warning

# oc get cm prometheus-k8s-rulefiles-0 -o yaml | grep -A 3 -B 5 kubelet_running_pod
      - alert: KubeletTooManyPods
        annotations:
          message: Kubelet {{$labels.instance}} is running {{$value}} pods, close to the
            limit of 110.
        expr: |
          kubelet_running_pod_count{job="kubelet"} > 90
        for: 15m
        labels:
          severity: warning
```
> after tens of seconds
```
# oc get prometheusrules prometheus-k8s-rules -o yaml | grep -A 3 -B 5 kubelet_running_pod
    - alert: KubeletTooManyPods
      annotations:
        message: Kubelet {{$labels.instance}} is running {{$value}} pods, close to
          the limit of 110.
      expr: |
        kubelet_running_pod_count{job="kubelet"} > 100
      for: 15m
      labels:
        severity: warning
```

**Environment**
```
# oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://lb.example.com:8443
openshift v3.11.0+84fe0ad-23
kubernetes v1.11.0+d4cacc0
```

* Prometheus Operator version:
```
# docker images | grep prometheus-operator
quay.io/coreos/prometheus-operator             v0.23.2             835a7e260b35        2 months ago        47 MB
```
