### ISSUE TITLE
Change Version of image

### ISSUE THREAD

**Issue by Reamer** [openshift/cluster-monitoring-operator#165]
Hi,
I try to change the version of my Prometheus image in a test environment.
Therefore I use the `cluster-monitoring-config`, but the version parameter has no effect.
```
...
prometheusK8s:
  baseImage: openshift/prometheus
  nodeSelector:
    node-role.kubernetes.io/infra: "true"
  externalLabels:
    cluster: s-openshift.mycompany.com
  version: v2.5.0
...
```
Is the version hard coded in cluster-monitoring-operator?

Thanks for your help in advance
