### ISSUE TITLE
Alerts generated by user-workload-monitoring are not included in remoteWrite

### ISSUE THREAD

**Issue by bo0ts** [openshift/cluster-monitoring-operator#1968]
We have a cluster with enabled user-workload-monitoring and forward all alerts to a out-of-cluster mimir instance.

This works for all alerts generated by cluster-monitoring, but alerts generated by user-workload-monitoring are not included in the remoteWrite. They show up in the console UI as every other alert. What is special about those alerts and why are they filtered? We tried several things including configuring remoteWrite for the user-workload prometheus instance but non had the desired effect.

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    alertmanagerMain:
      enableUserAlertmanagerConfig: true
    prometheusK8s:
      externalLabels:
        cluster: ourcluster
      remoteWrite:
        - url: https://mimir.../api/v1/push
          headers: 
            "X-Scope-OrgID": anonymous
          queueConfig:
            capacity: 30000
            maxSamplesPerSend: 10000
          writeRelabelConfigs:
          - sourceLabels: ["__name__"]
            regex: "(^ALERTS$|^ALERTS_FOR_STATE$)"
            action: keep
          - sourceLabels: ["severity"]
            action: replace
            targetLabel: okd_severity
          - regex: "(^prometheus$|__tmp_openshift_cluster_id__|^instance$|^severity$)"
            action: labeldrop
    enableUserWorkload: true

```

Example alerting rule:

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
  name: loki-loki-alerts
  namespace: grafana
spec:
  groups:
  - name: loki_alerts
    rules:
    - alert: LokiRequestErrors
      annotations:
        message: |
          {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf "%.2f" $value }}% errors.
      expr: |
        100 * sum(rate(loki_request_duration_seconds_count{status_code=~"5.."}[2m])) by (namespace, job, route)
          /
        sum(rate(loki_request_duration_seconds_count[2m])) by (namespace, job, route)
          > 10
      for: 15m
      labels:
        severity: critical
```
