### ISSUE TITLE
kubelet metrics not working in after upgrade to OKD 4.13

### ISSUE THREAD

**Issue by joyartoun** [openshift/cluster-monitoring-operator#2001]
Hi all,

I cannot for the life of me understand why this problem is occuring. All of the metric targets in the kube-system namespace is down. I have a identical cluster with the same config running in parallell and it's working fine there.

It looks like the following.
![image](https://github.com/openshift/cluster-monitoring-operator/assets/29835230/471cb173-f90b-4ef6-af94-54b242c769f4)

I am following the documentation and not doing anything that is not supported per openshift documentation and I don't understand why it's not working, any ideas?

The prometheus operator does not throw any error, neither is the cluster-monitoring-operator. The prometheus-k8s pods are working flawlessly.
The only difference between this cluster and the "parallell" one is that this one was upgraded from 4.11 to 4.13, the "parallell" one was deployed on 4.13 from the beginning.

Following is the cluster-monitoring config used.
```
enableUserWorkload: true
prometheusOperator:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
prometheusK8s:
  externalLabels:
    cluster: <redacted>
  remoteWrite:
  - url: http://<redacted>:8428/api/v1/write
  retention: 15d
  volumeClaimTemplate:
    metadata:
      name: prometheus
    spec:
      storageClassName: ceph-block
      volumeMode: Filesystem
      resources:
        requests:
          storage: 40Gi
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
alertmanagerMain:
  volumeClaimTemplate:
    metadata:
      name: alertmanager
    spec:
      storageClassName: ceph-block
      resources:
        requests:
          storage: 20Gi
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
kubeStateMetrics:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
grafana:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
telemeterClient:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
k8sPrometheusAdapter:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
openshiftStateMetrics:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
thanosQuerier:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"
```
No network policies exist in the openshift-monitoring namespace either.
4.13.0-0.okd-2023-05-22-052007 is the version running.
