### ISSUE TITLE
Support enableRemoteWriteReceiver flag in prometheus{,K8s} config

### ISSUE THREAD

**Issue by jirislav** [openshift/cluster-monitoring-operator#2217]
I need to deliver metrics from the [k6-operator](https://github.com/grafana/k6-operator) (testing framework from Grafana, runs in jobs) to Prometheus.

At the time of writing this issue, [K6 officially supports](https://k6.io/docs/results-output/real-time/prometheus-remote-write/) only the [Prometheus remote write](https://prometheus.io/docs/concepts/remote_write_spec/) as the only way to get the metrics there.

Since the CMO uses `CoreOS` Prometheus operator under the hood, it [should be possible](https://prometheus-operator.dev/docs/operator/api/) to extend the configuration in such a way so that the following is possible:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  enableRemoteWriteReceiver: true
```

By default, Prometheus has this feature disabled, resulting in `404 Not Found` when trying to use the API:
```json
{"error":"got status code: 404 instead expected a 2xx successful status code","level":"error","msg":"Failed to send the time series data to the endpoint","output":"Prometheus remote write"}
```

I would expect this to be configured in [the Cluster Monitoring Operator configuration](https://docs.openshift.com/dedicated/monitoring/config-map-reference-for-the-cluster-monitoring-operator.html#prometheusrestrictedconfig) in a way similar to these drafts:

```yaml
kind: ConfigMap
apiVersion: v1
data:
  config.yaml: |
    prometheusK8s:
      enableRemoteWriteReceiver: true
```

```yaml
kind: ConfigMap
apiVersion: v1
data:
  config.yaml: |
    prometheus:
      enableRemoteWriteReceiver: true
```
