### ISSUE TITLE
Why are there 3 alertmanager pods?

### ISSUE THREAD

**Issue by jeremyeder** [openshift/cluster-monitoring-operator#309]
Is there a technical reason that we require three alertmanager pods?

https://github.com/openshift/cluster-monitoring-operator/blob/dc3bfa19e6e375b0790cf231026ec0c371a66718/assets/alertmanager/alertmanager.yaml#L62

```
jeder@desktop: ~ $ oc get pods -n openshift-monitoring|egrep -i 'alert|name'
NAME                                           READY   STATUS    RESTARTS   AGE
alertmanager-main-0                            3/3     Running   0          46h
alertmanager-main-1                            3/3     Running   0          46h
alertmanager-main-2                            3/3     Running   0          46h
```

```
jeder@desktop: ~ $ oc version -o yaml                                                                                                                                                         
clientVersion:
  buildDate: "2019-04-02T17:55:35Z"
  compiler: ""
  gitCommit: acd551fb5
  gitTreeState: ""
  gitVersion: v4.0.22
  goVersion: ""
  major: "4"
  minor: 0+
  platform: ""
serverVersion:
  buildDate: "2019-04-02T23:08:07Z"
  compiler: gc
  gitCommit: 6d43744
  gitTreeState: clean
  gitVersion: v1.13.4+6d43744
  goVersion: go1.10.3
  major: "1"
  minor: 13+
  platform: linux/amd64
```
```
jeder@desktop: ~ $ oc get clusteroperators|egrep -i 'progress|monitor'                                                                                                                        
NAME                                 VERSION                           AVAILABLE   PROGRESSING   FAILING   SINCE                                                                              
monitoring                           4.0.0-0.alpha-2019-04-03-121923   True        False         False     2d3h                                                                               
```
