### ISSUE TITLE
Use specific template for altertmanager

### ISSUE THREAD

**Issue by camabeh** [openshift/cluster-monitoring-operator#325]
Hello, is there any way to use custom template for alertmanager?

```
.../opsgenie.tmpl:/etc/alertmanager/templates/opsgenie.tmpl:ro
```
and then using it
```
  - name: opsgenie
    opsgenie_configs:
      - api_key: ...
        send_resolved: true
        teams: SuperTeam
        tags: '{{ template "opsgenie.default.tags" .  }}'
        message: '{{ template "opsgenie.default.message" . }}'
        source: '{{ template "opsgenie.default.source" . }}'
        description: '{{ template "opsgenie.default.description" . }}'
        priority: '{{ template "opsgenie.default.priority_mapper" . }}'
```
