### ISSUE TITLE
remote write with tls config

### ISSUE THREAD

**Issue by marcolan018** [openshift/cluster-monitoring-operator#710]
Hi,
    I am trying to config the prometheus k8s to push metrics to remote server using remote writing configuration.
    The remote write endpoint requires tls configuration and I need to config the cert file path in the  remotewrite configuration. For that, I need to mount the secret which has the cert content into the prometheus pod, so that I can specify the cert file path. But seems it's not allowed to specify secrets? If that's true, any other option can help on my scenario? 
     thanks.

**Comment by lilic** [comment]
> I am trying to config the prometheus k8s to push metrics to remote server using remote writing configuration.

This is the configuration options we provide, they can be passed to the [remoteWrite](https://github.com/openshift/cluster-monitoring-operator/blob/f5aaabed6622874770ef83b707511990cf1191fd/pkg/manifests/config.go#L89)
by specifying the [RemoteWriteSpec](https://github.com/openshift/cluster-monitoring-operator/blob/f5aaabed6622874770ef83b707511990cf1191fd/vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go#L425:6)

The TLSConfig allows you pass the SecretOrConfigMap options, have you tried that?
https://github.com/openshift/cluster-monitoring-operator/blob/f5aaabed6622874770ef83b707511990cf1191fd/vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go#L729

**Comment by marcolan018** [comment]
@lilic 
thanks for response.
I tried the solution you mentioned but it cannot work.
here is the content for the config I used
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      remoteWrite:
        - url: "https://********"
          writeRelabelConfigs:
          - sourceLabels: [__name__]
            replacement: eidola_cluster
            targetLabel: cluster
          tlsConfig:
            ca:
              secret:
                name: client-certs
                key: ca.crt
            cert:
              secret:
                name: client-certs
                key: tls.crt
            keySecret:
              name: client-certs
              key: tls.key
            insecureSkipVerify: true
```
after apply the changes, prometheus k8s cannot work because the secret client-certs not mounted.
