### ISSUE TITLE
User workload alerts do not appear in OpenShift UI

### ISSUE THREAD

**Issue by astefanutti** [openshift/cluster-monitoring-operator#836]
I have configured user workload monitoring on an OpenShift 4.4.8 cluster according to: https://docs.openshift.com/container-platform/4.4/monitoring/monitoring-your-own-services.html.

While I can query the user workload metrics from the OpenShift monitoring UI, the user alerts do not appear in the _Alerting_ view.

I've tried using the example from the documentation, i.e.:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alert
  namespace: ns1
spec:
  groups:
  - name: example
    rules:
    - alert: VersionAlert
      expr: version{job="prometheus-example-app"} == 0
```

The `openshift-user-workload-monitoring/prometheus-user-workload-rulefiles-0` ConfigMap contains the corresponding alert, and the associated user workload metric is visible from the Thanos Querier UI.

I've tried setting the label `openshift.io/prometheus-rule-evaluation-scope: "leaf-prometheus"` on the PrometheusRule, as documented in [User workload monitoring](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/user-workload-monitoring.md), without success.

I've searched the logs from the pods in the `openshift-monitoring` and `openshift-user-workload-monitoring` for errors, but failed to find anything relevant.

Thanks for your help!
