### ISSUE TITLE
federate user workload prometheus

### ISSUE THREAD

**Issue by bomboom** [openshift/cluster-monitoring-operator#964]
Hi, I have a use case that one external Prometheus instance needs to federate user-workload Prometheus. Is there any way to do it?

I tried NodePort, however, thru kube_rbac_proxy, it's fobbiden to access /federate (only /metrics is allowed).
`Forbidden (user=system:serviceaccount:openshift-user-workload-monitoring:prometheus-user-workload, verb=get, resource=, subresource=)`

**Comment by jomeier** [comment]
Maybe this could be a solution?

https://github.com/openshift/cluster-monitoring-operator/issues/975

**Comment by sichvoge** [comment]
Do you need to federate for a central view? If so, my answer on #975 would also apply here.

**Comment by 4n4nd** [comment]
I was able to set up remote write from the user workload prometheus instance using the following config:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 7d
    techPreviewUserWorkload:
      enabled: true
    prometheusUserWorkload:
      remoteWrite:
        - url: "https://172.30.76.93:8081/api/metrics/v1/write"
```
